name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: draft
          path: draft.epub
