name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Update & upgrade
      #   run: |
      #     sudo apt update
      #     sudo apt upgrade
      - name: Install pandoc
        run: sudo apt install -y pandoc
      - name: TEST # TODO: Remove
        run: pandoc --version
      - name: Build draft
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: draft
          path: draft.epub
